version: '3.2'
services:
  mediator:
    image: ghcr.io/hyperledger/aries-framework-go:0.1.8
    command: "start --agent-default-label GoMediator"
    environment:
      - ARIESD_LOG_LEVEL=DEBUG
      - ARIESD_API_HOST=0.0.0.0:8080
      - ARIESD_AUTO_ACCEPT=true
      - ARIESD_DATABASE_TYPE=mem
      - ARIESD_INBOUND_HOST=http@0.0.0.0:8081,ws@0.0.0.0:8082
      - ARIESD_INBOUND_HOST_EXTERNAL=http@http://localhost:8081,ws@ws://localhost:8082
      - ARIESD_OUTBOUND_TRANSPORT=http,ws
      - ARIESD_WEBHOOK_URL=http://netcat:8083
      - ARIESD_TRANSPORT_RETURN_ROUTE=all
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082

  netcat:
    image: subfuzion/netcat:latest
    command: -vl 8083

  tcpdump:
    profiles:
      - debug
    image: nicolaka/netshoot
    depends_on:
      - mediator
    command: tcpdump -i eth0 -w /data/dump.pcap
    network_mode: service:mediator
    volumes:
      - $PWD/data:/data
